//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotConnectionSwitcher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2485")]
        public string TeamNumber {
            get {
                return ((string)(this["TeamNumber"]));
            }
            set {
                this["TeamNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iVBORw0KGgoAAAANSUhEUgAAADEAAABACAYAAACz4p94AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8Y" +
            "QUAAAcdSURBVGhD1Zp1jGxVEofRsGiwhbAEd3aR4O7yBwTbEGSDBgIESHALDgFCAsHdZdGFEFzDLu4Q+" +
            "APfhcey+9DgzvB9TdfLuXeqe2a675v35pd8kz7Vc6X6nnOqTp07xcDAwOTEZrBVzTYkqXGUmBZ2gFXbb" +
            "AynwN9hKlgatoTs2AqpcSIyHcwJ68JZkOk72Bp8IhdAdp4KqXEisCJcBm/CJ/ANdNIv8O3vHwd+hlthG" +
            "sjO2yI1Noxd49/Qq3RodsjO3SI1NsQMsCHcCL9CL/oAHOyOn+waLVJjjywGR8Kd8E94F3rVD/AG3A/Zt" +
            "SqkxhHyB9gcPoMm9BpsCifAKpBds0Jq7IKPdYX257nhEHgVmtJNYPc7Hf4M9eunpMYuOEgPhDPhf9C0/" +
            "EHOhoUgu35KahwCB1o/8kYfg/FtSr0Fy0B23Y6kxiHYB3qRQex92BemhoXhGPgrvAQGNsdXds2upMYuz" +
            "AgGrJHoXvg/2P2OBVMLz+XNrwYbwX5tW0+kxi5sD0PpJwhHjc5ngP3cm70DjNwO2oNgTwgHdoVh5Up1U" +
            "mMHpoSd4GGwWyjn869+/9jSl/AyHAr2fVMIdTCsDrvDx/AI3AJ/gzj/o2B0vhCMN2GfBex6HbtaahwGs" +
            "4Jz+V9gPjAy/wdOAh2wy1wK34MOvw7jwCfk2NDZbSDOZ250D4TuhvjuRNA5k8awVUiNPWJ03bFm+xR0y" +
            "qnZ8TQ/fA57Q/yPT/h20LnQPyC+v0QDWg/CViE19sjhcGXR9qaN4joRNlNxx0nZjWaDelb7EMT3F2lAo" +
            "/Ik1oRXIJK1cOKwdjtsOrFz0XaarcvIHceEE+tA2Cqkxh7xhhzMS7bbZrE64RMq/6d0Yl54HpwgSl0Lc" +
            "cx5GtBaELYKqbEPHBfOYH7WCcdE3Qlnp13AGcilqIHuRyjl+uO6NkZx5ZOO81RIjX1wHDgQ/Tw9+KuXY" +
            "yKehPHGRNJZKpPTrbOfPKABrQFxngqpsQ+MwN6An/8E/sLnt9uyANh1DHS234ZMZXdyqlbGmbBVSI19Y" +
            "Bd6EeYBb1hdD/H9UhrQyWD7nVZrsMpjnPGUP1DYKqTGPjFQGcjmAlX+qktoQAYw2/XVn4HRpWzmhGWds" +
            "FVIjX1yFJgvubhXw3XCm3f8+CRNSeKYcKLjKi819sn6YH5lOqKcYeK7cMKlp+16FcRk8F9gmSaOCScs+" +
            "4StQmrsk5nAwe28Xu8adSfMt0rtBk/CzRDH3AZqVJ2QG8D1twngSJwwNX8KyojtGFOxth9EamwA+/ZdY" +
            "E5kQAu70Vx1csIU5BnwR4hjLAGp5SFsFVJjAzinm3pbhiyfROmE2WvdCVN40xCzWNP9P4LJoFoOymtMI" +
            "DU2gJH5v6CugbBHnDgVrJgYDGPhpIzg2jzWbiQfgWNrWSivMYHU2BCxyCmn2HDiCDAJvA8e19CWs5IB0" +
            "CnWFZ2pS5ynYxUkNTbEaaBKJ9xzUHYn19tOx5EbKXOvpyEbE64iw1YhNTaEN6jKMWGBwO5jfIglqFNqy" +
            "HTkOSidcIJQHSuCqbEhvKgqZ6dwQm0A2pyNQkZynSgDZDhhVwxbhdTYEFYolLXVsDk4lePA2Ulb6YTdz" +
            "O5UdsFwwhgTtgqpsSEWBZU5EVmslE4cDS/AVRDfx5iYbJzYRAOytBO20gnXGa70Lof4fpLFCVkEVDkmz" +
            "ImU5cyw2X1CVtwtvlkljO9jCnZmC1uF1NgQC4LyJm2vBFEQcBfI6dQ6lN0n5JOwYlKuBs2llE82bBVSY" +
            "wNYLPOiJoCW7w1e2U7S12DtNvQemG85BVvqdKay+mf64j53dq3GnbAcuRe4sHHbqrzBfqWDpiqDrjvI0" +
            "AcWt8rANTHkUxq0HVxp9IillAeh123ekWpQObPSGCEmZFdAk11mOHINX7mXSmOYGIndQ4hXF0ZbZV7Vo" +
            "tIYgpnBedzS5KSUaw2nZ+/FkumC2c2a0ywO5vvm9+4duCnYqVo3qfVS3Liv72wB54DBx/l9rGi8Dvhek" +
            "bubY1XjdMJF+VjWRzphvx+r+hD2HqtO2P3dRrNo3ZpiXQOPJTlLum3gvbfwz8pwPLiuNffxEbnBbuY4O" +
            "apc9U1woo6VN5O5L2ByVLkH2KLSKHCTpK5n4VxwfWBBy0pdVOdGQ25AujKcAyr3W2kUrA2l3O1/ApwE7" +
            "JMuL13k+K6Gbwj4cokvHTYtz+kqbw9wCy27145O+D7S1eC4MFeydro/+CQuBpMwHfI1IN/b8HPUXutyf" +
            "Lmg8VzOKmXttZs8ru93AM2hTLfdMLetYy5IfLXNIpibKNuCewqmxzrqHnUp0xcnCpebpuyuoev/U5fd1" +
            "E398tWJrqTGHvCdDcvw7vSELAr4qp1OW+3bDg4A9/M6vfjl/oRVDc+XXSclNfaJuZiVvI67neCiP1PH8" +
            "n03UuMoYdeyjG9Rwa7jPrX74Nn/dmFgit8A/RmWOKrGcPwAAAAASUVORK5CYII=")]
        public string RobotImage {
            get {
                return ((string)(this["RobotImage"]));
            }
            set {
                this["RobotImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
    }
}
