//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotConnectionSwitcher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2485")]
        public string TeamNumber {
            get {
                return ((string)(this["TeamNumber"]));
            }
            set {
                this["TeamNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iVBORw0KGgoAAAANSUhEUgAAAD0AAABACAYAAACp3n/2AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8Y" +
            "QUAAAUmSURBVGhD5dtXiCRVFIDhNWAOq5hFUVkTgogoBsSEYsIIRkwYHtwHQURREEVBDJgwgBEFFcTIK" +
            "mJY1AdzBlFRVNQ155zD+P89Xcud2jPTO9N1OowHPmb6VPV03emqWzfVjJGRkV46Gl/hEszGAVgF0b5pw" +
            "mSiy2FciMNGfx25E9G+acJkovtQxU/tn08h2jdNmEx0B/7BK/gFxttYEtH+KcJkogfwcvv3lfEYLPSi7" +
            "VxPhMlEFtiCV68vxeeYtt+0BfsMVxW5U/EnVi9y6cJkktVgAU8vcofC2BjlvqnCZJJNYRyMKrejCWInl" +
            "PumCpNJdoWxA6qc37DhN17umypMJjkKxixUuVXxB7y2y31Thckk5+BXrFTklsIXuKzIpQuTSW7EPCxe5" +
            "PQa7q7lUoXJJI/juVpOc/FMLZcqTCZ5HdE3ehPeR89aZWEywbL4BrbA6tvOhZ2PFYtcqjCZYE38jVOKX" +
            "OV4/It1ilyqMJlgCxgHor5tTxhbor4tRZhMUBVsW9S3bQXDferbUoTJBCfCWA/1bZ7Wxgmob0sRJhOcj" +
            "58xs8hVlscPOK/IpQqTCW7DB4huS4vgPXjrqm9LESYTPImJxsLcZiMl2ta4MNmw6pu8q8jV3Q4bL9G2x" +
            "oXJBtmLuhnGeIVeGy/izSKXKkw2ZD98iCrugYOB62MtWIHtC88C4yVEf6dxYbJL1tDXoR4OFf0Ih36/g" +
            "11Kc1UMbaF3xzuYSgxdoe1QOGXjQP5UY6gKvR2sebuNoSj0ErBbWF6X3cTAF9pe0/NoMpzf8p4efV6jw" +
            "mQHdgGrGccm41N4S4s+s1FhsoMLkBHfwsGG6DMbFSY7eBZZ4XCSdUX0uY0JkxOw7/s9MsM57NRrO0xOY" +
            "H/0Ik5D9PmNCJPj8L9vn7cX4ZTuGoiOo2thsrAu7Cg8jY/giGav4mREx9S1MFk4A/2KRxEdU9fCZNvSe" +
            "AP9io+RMgEQJtt6VWmNF3ZB7XtHx9aVMNk2B/2OXRAdW1fCJDaHk+X9jnJRTmPCJC7GIIRrzJZBdIxTF" +
            "iVdoGolMiixB6LjlONsR2CzItdRlHTJ0yDFrfC4HHs7CCfBnp7zYtvgIdjNXQz1soSqX1zl4+ofRyczO" +
            "xRTCQcRn4CtNOM3OGS8Gzx2vyRnT/xpGY6DzdiLYJ1wC17FkZhfaAvazdhWv8Lh5U/wO6qWosNWV+BMH" +
            "INr4a3PeTTz8wv9MKZLeDZ4VtwAJwQdmHAt6llwZdNeaBW66WGfQYzqTLDgsy30la2X/5+YZ6HtSXmxW" +
            "xm49mO6hRWflfOX8BmSWa0Lu81GgLcBF8MMWg0+2XAlkzW4Y/KbYAN4fW+I8D6tah3IsEZ1b6+4StHpp" +
            "kN8XW4obQRvBcMc16Askx0onxIat9AuSLeqd5ZxEMPO0F+jv44b1k8P4nqcDWdQWo9SRAUuOU5l088RS" +
            "qdW+x0uqHU01jUsCzMq69nqetRH4KIAr/GOhS6tgJ3hP8CasNuYzJ3C6/FwuGzaTsY+WJh4F44AjSnLm" +
            "BeT4PTL3rgab2GytzqXWmyPe1uvRr/B+2Fb2VtMPeorDavHIDqFqxwW6JqOeTFFzkhsDZt6rhKKDroK5" +
            "8A8ECcAfa89J3tMy7VfO8zsLbM8kzw1y8+T/3RHZztF9N5GCl3nPdHVfz5i+DVs+jlebq/HRxm8TKL3l" +
            "axIfQjVJrJnRLSPj0B0ilZbu26BRMM8eBsEGdM0/s1q5VIUPj4RvS+90NlcgXgsXoBP8nmHsbZuNUJiI" +
            "zP+A+ej2S6RkTbqAAAAAElFTkSuQmCC")]
        public string RobotImage {
            get {
                return ((string)(this["RobotImage"]));
            }
            set {
                this["RobotImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
    }
}
